# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Nexys4DDR_Master.xdc

# Block Designs: bd/programator/programator.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator || ORIG_REF_NAME==programator}]

# IP: bd/programator/ip/programator_microblaze_0_0/programator_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_microblaze_0_0 || ORIG_REF_NAME==programator_microblaze_0_0}]

# IP: bd/programator/ip/programator_dlmb_v10_0/programator_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_dlmb_v10_0 || ORIG_REF_NAME==programator_dlmb_v10_0}]

# IP: bd/programator/ip/programator_ilmb_v10_0/programator_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_ilmb_v10_0 || ORIG_REF_NAME==programator_ilmb_v10_0}]

# IP: bd/programator/ip/programator_dlmb_bram_if_cntlr_0/programator_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==programator_dlmb_bram_if_cntlr_0}]

# IP: bd/programator/ip/programator_ilmb_bram_if_cntlr_0/programator_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==programator_ilmb_bram_if_cntlr_0}]

# IP: bd/programator/ip/programator_lmb_bram_0/programator_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_lmb_bram_0 || ORIG_REF_NAME==programator_lmb_bram_0}]

# IP: bd/programator/ip/programator_microblaze_0_axi_periph_0/programator_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_microblaze_0_axi_periph_0 || ORIG_REF_NAME==programator_microblaze_0_axi_periph_0}]

# IP: bd/programator/ip/programator_microblaze_0_axi_intc_0/programator_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_microblaze_0_axi_intc_0 || ORIG_REF_NAME==programator_microblaze_0_axi_intc_0}]

# IP: bd/programator/ip/programator_microblaze_0_xlconcat_0/programator_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_microblaze_0_xlconcat_0 || ORIG_REF_NAME==programator_microblaze_0_xlconcat_0}]

# IP: bd/programator/ip/programator_mdm_1_0/programator_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_mdm_1_0 || ORIG_REF_NAME==programator_mdm_1_0}]

# IP: bd/programator/ip/programator_clk_wiz_1_0/programator_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_clk_wiz_1_0 || ORIG_REF_NAME==programator_clk_wiz_1_0}]

# IP: bd/programator/ip/programator_rst_clk_wiz_1_100M_0/programator_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==programator_rst_clk_wiz_1_100M_0}]

# IP: bd/programator/ip/programator_axi_uartlite_0_0/programator_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_axi_uartlite_0_0 || ORIG_REF_NAME==programator_axi_uartlite_0_0}]

# IP: bd/programator/ip/programator_axi_quad_spi_0_0/programator_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_axi_quad_spi_0_0 || ORIG_REF_NAME==programator_axi_quad_spi_0_0}]

# IP: bd/programator/ip/programator_axi_gpio_0_0/programator_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_axi_gpio_0_0 || ORIG_REF_NAME==programator_axi_gpio_0_0}]

# IP: bd/programator/ip/programator_xbar_0/programator_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_xbar_0 || ORIG_REF_NAME==programator_xbar_0}]

# IP: bd/programator/ip/programator_mig_7series_0_0/programator_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_mig_7series_0_0 || ORIG_REF_NAME==programator_mig_7series_0_0}]

# IP: bd/programator/ip/programator_rst_mig_7series_0_81M_0/programator_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==programator_rst_mig_7series_0_81M_0}]

# IP: bd/programator/ip/programator_auto_ds_0/programator_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_auto_ds_0 || ORIG_REF_NAME==programator_auto_ds_0}]

# IP: bd/programator/ip/programator_auto_pc_0/programator_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_auto_pc_0 || ORIG_REF_NAME==programator_auto_pc_0}]

# IP: bd/programator/ip/programator_auto_ds_1/programator_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_auto_ds_1 || ORIG_REF_NAME==programator_auto_ds_1}]

# IP: bd/programator/ip/programator_auto_pc_1/programator_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_auto_pc_1 || ORIG_REF_NAME==programator_auto_pc_1}]

# IP: bd/programator/ip/programator_auto_ds_2/programator_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_auto_ds_2 || ORIG_REF_NAME==programator_auto_ds_2}]

# IP: bd/programator/ip/programator_auto_pc_2/programator_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_auto_pc_2 || ORIG_REF_NAME==programator_auto_pc_2}]

# IP: bd/programator/ip/programator_auto_ds_3/programator_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_auto_ds_3 || ORIG_REF_NAME==programator_auto_ds_3}]

# IP: bd/programator/ip/programator_auto_pc_3/programator_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_auto_pc_3 || ORIG_REF_NAME==programator_auto_pc_3}]

# IP: bd/programator/ip/programator_auto_cc_0/programator_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_auto_cc_0 || ORIG_REF_NAME==programator_auto_cc_0}]

# IP: bd/programator/ip/programator_auto_pc_4/programator_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_auto_pc_4 || ORIG_REF_NAME==programator_auto_pc_4}]

# IP: bd/programator/ip/programator_auto_us_0/programator_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_auto_us_0 || ORIG_REF_NAME==programator_auto_us_0}]

# IP: bd/programator/ip/programator_auto_us_1/programator_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_auto_us_1 || ORIG_REF_NAME==programator_auto_us_1}]

# IP: bd/programator/ip/programator_auto_us_2/programator_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_auto_us_2 || ORIG_REF_NAME==programator_auto_us_2}]

# XDC: bd/programator/ip/programator_microblaze_0_0/programator_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==programator_microblaze_0_0 || ORIG_REF_NAME==programator_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/programator/ip/programator_microblaze_0_0/programator_microblaze_0_0_ooc_debug.xdc

# XDC: bd/programator/ip/programator_microblaze_0_0/programator_microblaze_0_0_ooc.xdc

# XDC: bd/programator/ip/programator_dlmb_v10_0/programator_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==programator_dlmb_v10_0 || ORIG_REF_NAME==programator_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/programator/ip/programator_dlmb_v10_0/programator_dlmb_v10_0_ooc.xdc

# XDC: bd/programator/ip/programator_ilmb_v10_0/programator_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==programator_ilmb_v10_0 || ORIG_REF_NAME==programator_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/programator/ip/programator_ilmb_v10_0/programator_ilmb_v10_0_ooc.xdc

# XDC: bd/programator/ip/programator_dlmb_bram_if_cntlr_0/programator_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/programator/ip/programator_ilmb_bram_if_cntlr_0/programator_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/programator/ip/programator_lmb_bram_0/programator_lmb_bram_0_ooc.xdc

# XDC: bd/programator/ip/programator_microblaze_0_axi_intc_0/programator_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==programator_microblaze_0_axi_intc_0 || ORIG_REF_NAME==programator_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/programator/ip/programator_microblaze_0_axi_intc_0/programator_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==programator_microblaze_0_axi_intc_0 || ORIG_REF_NAME==programator_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/programator/ip/programator_microblaze_0_axi_intc_0/programator_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/programator/ip/programator_mdm_1_0/programator_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==programator_mdm_1_0 || ORIG_REF_NAME==programator_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/programator/ip/programator_mdm_1_0/programator_mdm_1_0_ooc_trace.xdc

# XDC: bd/programator/ip/programator_clk_wiz_1_0/programator_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==programator_clk_wiz_1_0 || ORIG_REF_NAME==programator_clk_wiz_1_0}] {/U0 }]/U0 ]]

# XDC: bd/programator/ip/programator_clk_wiz_1_0/programator_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==programator_clk_wiz_1_0 || ORIG_REF_NAME==programator_clk_wiz_1_0}] {/U0 }]/U0 ]]

# XDC: bd/programator/ip/programator_clk_wiz_1_0/programator_clk_wiz_1_0_ooc.xdc

# XDC: bd/programator/ip/programator_rst_clk_wiz_1_100M_0/programator_rst_clk_wiz_1_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==programator_rst_clk_wiz_1_100M_0}]

# XDC: bd/programator/ip/programator_rst_clk_wiz_1_100M_0/programator_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==programator_rst_clk_wiz_1_100M_0}]

# XDC: bd/programator/ip/programator_rst_clk_wiz_1_100M_0/programator_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/programator/ip/programator_axi_uartlite_0_0/programator_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==programator_axi_uartlite_0_0 || ORIG_REF_NAME==programator_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/programator/ip/programator_axi_uartlite_0_0/programator_axi_uartlite_0_0_ooc.xdc

# XDC: bd/programator/ip/programator_axi_uartlite_0_0/programator_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==programator_axi_uartlite_0_0 || ORIG_REF_NAME==programator_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/programator/ip/programator_axi_quad_spi_0_0/programator_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==programator_axi_quad_spi_0_0 || ORIG_REF_NAME==programator_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/programator/ip/programator_axi_quad_spi_0_0/programator_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==programator_axi_quad_spi_0_0 || ORIG_REF_NAME==programator_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/programator/ip/programator_axi_quad_spi_0_0/programator_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/programator/ip/programator_axi_quad_spi_0_0/programator_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==programator_axi_quad_spi_0_0 || ORIG_REF_NAME==programator_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/programator/ip/programator_axi_gpio_0_0/programator_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==programator_axi_gpio_0_0 || ORIG_REF_NAME==programator_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/programator/ip/programator_axi_gpio_0_0/programator_axi_gpio_0_0_ooc.xdc

# XDC: bd/programator/ip/programator_axi_gpio_0_0/programator_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==programator_axi_gpio_0_0 || ORIG_REF_NAME==programator_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/programator/ip/programator_xbar_0/programator_xbar_0_ooc.xdc

# XDC: bd/programator/ip/programator_mig_7series_0_0/programator_mig_7series_0_0/user_design/constraints/programator_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_mig_7series_0_0 || ORIG_REF_NAME==programator_mig_7series_0_0}]

# XDC: bd/programator/ip/programator_mig_7series_0_0/programator_mig_7series_0_0/user_design/constraints/programator_mig_7series_0_0_ooc.xdc

# XDC: bd/programator/ip/programator_mig_7series_0_0/programator_mig_7series_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_mig_7series_0_0 || ORIG_REF_NAME==programator_mig_7series_0_0}]

# XDC: bd/programator/ip/programator_rst_mig_7series_0_81M_0/programator_rst_mig_7series_0_81M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==programator_rst_mig_7series_0_81M_0}]

# XDC: bd/programator/ip/programator_rst_mig_7series_0_81M_0/programator_rst_mig_7series_0_81M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programator_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==programator_rst_mig_7series_0_81M_0}]

# XDC: bd/programator/ip/programator_rst_mig_7series_0_81M_0/programator_rst_mig_7series_0_81M_0_ooc.xdc

# XDC: bd/programator/ip/programator_auto_ds_0/programator_auto_ds_0_ooc.xdc

# XDC: bd/programator/ip/programator_auto_ds_0/programator_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==programator_auto_ds_0 || ORIG_REF_NAME==programator_auto_ds_0}] {/inst }]/inst ]]

# XDC: bd/programator/ip/programator_auto_pc_0/programator_auto_pc_0_ooc.xdc

# XDC: bd/programator/ip/programator_auto_ds_1/programator_auto_ds_1_ooc.xdc

# XDC: bd/programator/ip/programator_auto_ds_1/programator_auto_ds_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==programator_auto_ds_1 || ORIG_REF_NAME==programator_auto_ds_1}] {/inst }]/inst ]]

# XDC: bd/programator/ip/programator_auto_pc_1/programator_auto_pc_1_ooc.xdc

# XDC: bd/programator/ip/programator_auto_ds_2/programator_auto_ds_2_ooc.xdc

# XDC: bd/programator/ip/programator_auto_ds_2/programator_auto_ds_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==programator_auto_ds_2 || ORIG_REF_NAME==programator_auto_ds_2}] {/inst }]/inst ]]

# XDC: bd/programator/ip/programator_auto_pc_2/programator_auto_pc_2_ooc.xdc

# XDC: bd/programator/ip/programator_auto_ds_3/programator_auto_ds_3_ooc.xdc

# XDC: bd/programator/ip/programator_auto_ds_3/programator_auto_ds_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==programator_auto_ds_3 || ORIG_REF_NAME==programator_auto_ds_3}] {/inst }]/inst ]]

# XDC: bd/programator/ip/programator_auto_pc_3/programator_auto_pc_3_ooc.xdc

# XDC: bd/programator/ip/programator_auto_cc_0/programator_auto_cc_0_ooc.xdc

# XDC: bd/programator/ip/programator_auto_cc_0/programator_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==programator_auto_cc_0 || ORIG_REF_NAME==programator_auto_cc_0}] {/inst }]/inst ]]

# XDC: bd/programator/ip/programator_auto_pc_4/programator_auto_pc_4_ooc.xdc

# XDC: bd/programator/ip/programator_auto_us_0/programator_auto_us_0_ooc.xdc

# XDC: bd/programator/ip/programator_auto_us_0/programator_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==programator_auto_us_0 || ORIG_REF_NAME==programator_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/programator/ip/programator_auto_us_1/programator_auto_us_1_ooc.xdc

# XDC: bd/programator/ip/programator_auto_us_1/programator_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==programator_auto_us_1 || ORIG_REF_NAME==programator_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/programator/ip/programator_auto_us_2/programator_auto_us_2_ooc.xdc

# XDC: bd/programator/ip/programator_auto_us_2/programator_auto_us_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==programator_auto_us_2 || ORIG_REF_NAME==programator_auto_us_2}] {/inst }]/inst ]]

# XDC: bd/programator/programator_ooc.xdc
