# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.cache/wt [current_project]
set_property parent.project_path D:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files D:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.sdk/programator/Debug/programator.elf
set_property SCOPED_TO_REF programator [get_files -all D:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.sdk/programator/Debug/programator.elf]
set_property SCOPED_TO_CELLS microblaze_0 [get_files -all D:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.sdk/programator/Debug/programator.elf]
add_files D:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/programator.bd
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_microblaze_0_0/programator_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_microblaze_0_0/programator_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_microblaze_0_0/programator_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_dlmb_v10_0/programator_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_dlmb_v10_0/programator_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_ilmb_v10_0/programator_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_ilmb_v10_0/programator_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_dlmb_bram_if_cntlr_0/programator_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_ilmb_bram_if_cntlr_0/programator_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_lmb_bram_0/programator_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_microblaze_0_axi_intc_0/programator_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_microblaze_0_axi_intc_0/programator_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_microblaze_0_axi_intc_0/programator_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_mdm_1_0/programator_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_mdm_1_0/programator_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_clk_wiz_1_0/programator_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_clk_wiz_1_0/programator_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_clk_wiz_1_0/programator_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_rst_clk_wiz_1_100M_0/programator_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_rst_clk_wiz_1_100M_0/programator_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_rst_clk_wiz_1_100M_0/programator_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_axi_uartlite_0_0/programator_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_axi_uartlite_0_0/programator_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_axi_uartlite_0_0/programator_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_axi_quad_spi_0_0/programator_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_axi_quad_spi_0_0/programator_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_axi_quad_spi_0_0/programator_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_axi_quad_spi_0_0/programator_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_axi_gpio_0_0/programator_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_axi_gpio_0_0/programator_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_axi_gpio_0_0/programator_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_xbar_0/programator_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_mig_7series_0_0/programator_mig_7series_0_0/user_design/constraints/programator_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_mig_7series_0_0/programator_mig_7series_0_0/user_design/constraints/programator_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_mig_7series_0_0/programator_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_rst_mig_7series_0_81M_0/programator_rst_mig_7series_0_81M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_rst_mig_7series_0_81M_0/programator_rst_mig_7series_0_81M_0.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_rst_mig_7series_0_81M_0/programator_rst_mig_7series_0_81M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_auto_ds_0/programator_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_auto_ds_0/programator_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_auto_pc_0/programator_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_auto_ds_1/programator_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_auto_ds_1/programator_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_auto_pc_1/programator_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_auto_ds_2/programator_auto_ds_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_auto_ds_2/programator_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_auto_pc_2/programator_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_auto_ds_3/programator_auto_ds_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_auto_ds_3/programator_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_auto_pc_3/programator_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_auto_cc_0/programator_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_auto_cc_0/programator_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_auto_pc_4/programator_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_auto_us_0/programator_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_auto_us_0/programator_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_auto_us_1/programator_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_auto_us_1/programator_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_auto_us_2/programator_auto_us_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/ip/programator_auto_us_2/programator_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all D:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/programator_ooc.xdc]
set_property is_locked true [get_files D:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/bd/programator/programator.bd]

read_vhdl -library xil_defaultlib {
  D:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/new/ALU_mock.vhd
  D:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/new/program_memory.vhd
  D:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/new/marker_memory.vhd
  D:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/new/IO_controller.vhd
  D:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/new/DIO_module_mock.vhd
  D:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/new/CPU.vhd
  D:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/new/7seg_driver.vhd
  D:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/sources_1/new/top_lvl.vhd
}
read_xdc D:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files D:/Dropbox/dr/mgr/Workspaces/Vivado/CPUv1/CPUv1.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top top_lvl -part xc7a100tcsg324-1
write_checkpoint -noxdef top_lvl.dcp
catch { report_utilization -file top_lvl_utilization_synth.rpt -pb top_lvl_utilization_synth.pb }
